-- "Tenho interesse" em um estabelecimento: registra quem se interessou, para que
-- outras pessoas interessadas no mesmo imóvel possam se ver e se falar (dividir o
-- aluguel juntas), além de falar com o dono.

CREATE TABLE interesses (
    id          NUMBER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anuncio_id  NUMBER      NOT NULL,
    usuario_id  NUMBER      NOT NULL,
    criado_em   TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_interesses_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE CASCADE,
    CONSTRAINT fk_interesses_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uq_interesses_anuncio_usuario UNIQUE (anuncio_id, usuario_id)
);

CREATE INDEX idx_interesses_usuario ON interesses (usuario_id);

-- Uma "conversa" até aqui era sempre inquilino x dono do anúncio. Para permitir
-- também inquilino x inquilino (duas pessoas interessadas no mesmo imóvel se
-- falando), adiciona um segundo participante opcional: nulo = conversa com o dono
-- (comportamento de sempre); preenchido = conversa entre inquilino e usuario2.
ALTER TABLE conversas ADD (usuario2_id NUMBER);

ALTER TABLE conversas ADD CONSTRAINT fk_conversas_usuario2
    FOREIGN KEY (usuario2_id) REFERENCES usuarios (id) ON DELETE CASCADE;

ALTER TABLE conversas DROP CONSTRAINT uq_conversas_anuncio_inquilino;

-- No máximo uma conversa por (anúncio, inquilino) com o dono.
CREATE UNIQUE INDEX uq_conversas_com_dono ON conversas (
    CASE WHEN usuario2_id IS NULL THEN anuncio_id END,
    CASE WHEN usuario2_id IS NULL THEN inquilino_id END
);

-- No máximo uma conversa por (anúncio, par de interessados), independente de quem
-- iniciou — por isso usa o menor/maior id do par para o índice enxergar os dois
-- sentidos como a mesma combinação.
CREATE UNIQUE INDEX uq_conversas_entre_interessados ON conversas (
    CASE WHEN usuario2_id IS NOT NULL THEN anuncio_id END,
    CASE WHEN usuario2_id IS NOT NULL THEN LEAST(inquilino_id, usuario2_id) END,
    CASE WHEN usuario2_id IS NOT NULL THEN GREATEST(inquilino_id, usuario2_id) END
);
