CREATE TABLE redefinicoes_senha (
    id          NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER              NOT NULL,
    token_hash  VARCHAR2(64 CHAR)   NOT NULL,
    usado       VARCHAR2(3 CHAR)    DEFAULT 'NAO' NOT NULL,
    criado_em   TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    expira_em   TIMESTAMP           NOT NULL,
    CONSTRAINT fk_redefinicoes_senha_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_redefinicoes_senha_usado CHECK (usado IN ('SIM', 'NAO'))
);

CREATE UNIQUE INDEX uq_redefinicoes_senha_token ON redefinicoes_senha (token_hash);
CREATE INDEX idx_redefinicoes_senha_usuario ON redefinicoes_senha (usuario_id);
