-- Foto de perfil fica numa tabela separada (não como coluna em usuarios) de propósito:
-- assim carregar um usuário nas listagens normais (anúncios, conversas, busca) nunca
-- arrasta o BLOB junto, só quando a foto é pedida explicitamente pelo endpoint dela.
CREATE TABLE fotos_usuario (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER              NOT NULL,
    conteudo        BLOB                NOT NULL,
    tipo_conteudo   VARCHAR2(50 CHAR)   NOT NULL,
    atualizado_em   TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_fotos_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_fotos_usuario_usuario ON fotos_usuario (usuario_id);
