-- Fotos do imóvel/vaga anunciado. Igual às fotos de perfil, ficam numa tabela própria
-- para o BLOB não ser carregado junto quando o anúncio aparece em listagens.
CREATE TABLE fotos_anuncio (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anuncio_id      NUMBER              NOT NULL,
    conteudo        BLOB                NOT NULL,
    tipo_conteudo   VARCHAR2(50 CHAR)   NOT NULL,
    ordem           NUMBER(3)           DEFAULT 0 NOT NULL,
    criado_em       TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_fotos_anuncio_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE CASCADE
);

CREATE INDEX idx_fotos_anuncio_anuncio ON fotos_anuncio (anuncio_id);
