CREATE TABLE users (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(120 CHAR)  NOT NULL,
    email           VARCHAR2(180 CHAR)  NOT NULL,
    password_hash   VARCHAR2(255 CHAR)  NOT NULL,
    birth_date      DATE                NOT NULL,
    role            VARCHAR2(20 CHAR)   NOT NULL,
    occupation      VARCHAR2(160 CHAR),
    bio             VARCHAR2(1000 CHAR),
    created_at      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('RENTER', 'ADVERTISER'))
);

CREATE TABLE user_profiles (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER              NOT NULL,
    smoker          NUMBER(1),
    drinks_alcohol  NUMBER(1),
    vegetarian      NUMBER(1),
    has_pets        NUMBER(1),
    likes_animals   NUMBER(1),
    allergies       VARCHAR2(500 CHAR),
    music_taste     VARCHAR2(500 CHAR),
    routine         VARCHAR2(20 CHAR),
    updated_at      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_profiles_bools CHECK (
        smoker         IN (0, 1) AND drinks_alcohol IN (0, 1) AND vegetarian IN (0, 1)
        AND has_pets   IN (0, 1) AND likes_animals  IN (0, 1)
    ),
    CONSTRAINT ck_user_profiles_routine CHECK (routine IN ('DIURNO', 'NOTURNO', 'MISTO'))
);

CREATE TABLE listings (
    id                      NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 NUMBER              NOT NULL,
    type                    VARCHAR2(20 CHAR)   NOT NULL,
    title                   VARCHAR2(160 CHAR)  NOT NULL,
    description             VARCHAR2(2000 CHAR),
    preferred_neighborhood  VARCHAR2(160 CHAR),
    near_college            VARCHAR2(160 CHAR),
    price                   NUMBER(10, 2),
    address                 VARCHAR2(255 CHAR),
    latitude                FLOAT(53),
    longitude               FLOAT(53),
    accepts_pets            NUMBER(1),
    accepts_smoker          NUMBER(1),
    active                  NUMBER(1)           DEFAULT 1 NOT NULL,
    created_at              TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_listings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_listings_type CHECK (type IN ('PROCURANDO', 'TEM_VAGA', 'ESTABELECIMENTO')),
    CONSTRAINT ck_listings_active CHECK (active IN (0, 1)),
    CONSTRAINT ck_listings_accepts CHECK (accepts_pets IN (0, 1) AND accepts_smoker IN (0, 1))
);

-- Oracle não tem índice parcial: o CASE devolve NULL fora da condição, e NULLs não
-- entram no índice único. Resultado: no máximo uma busca (PROCURANDO) ativa por usuário.
CREATE UNIQUE INDEX uq_listings_one_procurando_per_user
    ON listings (CASE WHEN active = 1 AND type = 'PROCURANDO' THEN user_id END);

CREATE INDEX idx_listings_user ON listings (user_id);
CREATE INDEX idx_listings_type_active ON listings (type, active);

CREATE TABLE conversations (
    id              NUMBER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id      NUMBER      NOT NULL,
    renter_id       NUMBER      NOT NULL,
    created_at      TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_conversations_listing FOREIGN KEY (listing_id) REFERENCES listings (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversations_renter FOREIGN KEY (renter_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_conversations_listing_renter UNIQUE (listing_id, renter_id)
);

CREATE INDEX idx_conversations_renter ON conversations (renter_id);

CREATE TABLE messages (
    id                  NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     NUMBER              NOT NULL,
    sender_id           NUMBER              NOT NULL,
    content             VARCHAR2(2000 CHAR) NOT NULL,
    sent_at             TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_messages_conversation ON messages (conversation_id, sent_at);
