-- Schema inicial do RachaAi em PostgreSQL. Substitui o histórico de 35 migrations que existiu
-- em Oracle: como o projeto ainda não tinha ido para produção (sem dados reais a preservar),
-- a troca de banco foi feita consolidando o estado final direto num baseline novo, em vez de
-- traduzir cada ALTER TABLE Oracle um a um. RLS (políticas por linha) fica na V2, separado.

CREATE TABLE usuarios (
    id                          BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                        VARCHAR(120)        NOT NULL,
    email                       VARCHAR(180)        NOT NULL,
    senha_hash                  VARCHAR(255)        NOT NULL,
    data_nascimento             DATE                NOT NULL,
    cpf                         VARCHAR(11),
    alugar                      BOOLEAN             NOT NULL DEFAULT FALSE,
    anunciar                    BOOLEAN             NOT NULL DEFAULT FALSE,
    tipo_anunciante             VARCHAR(20),
    ocupacao                    VARCHAR(160),
    bio                         VARCHAR(1000),
    criado_em                   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    termos_seguranca_aceito_em  TIMESTAMP,
    admin                       BOOLEAN             NOT NULL DEFAULT FALSE,
    bloqueado_em                TIMESTAMP,
    motivo_bloqueio             VARCHAR(500),
    bloqueado_por_id            BIGINT,
    versao_token                INTEGER             NOT NULL DEFAULT 0,
    termos_aceitos_em           TIMESTAMP,
    versao_termos               VARCHAR(20),
    excluido_em                 TIMESTAMP,
    email_confirmado_em         TIMESTAMP,
    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT uq_usuarios_cpf UNIQUE (cpf),
    CONSTRAINT fk_usuarios_bloqueado_por FOREIGN KEY (bloqueado_por_id) REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_usuarios_tipo_anunciante CHECK (tipo_anunciante IS NULL OR tipo_anunciante IN ('VAGA', 'ESTABELECIMENTO')),
    CONSTRAINT ck_usuarios_papel_minimo CHECK (alugar OR anunciar)
);

CREATE TABLE perfis_usuario (
    id                      BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id              BIGINT              NOT NULL,
    habito_fumo             VARCHAR(30),
    habito_bebida           VARCHAR(30),
    alimentacao             VARCHAR(20),
    alimentacao_outro       VARCHAR(160),
    sexo                    VARCHAR(20),
    pet_preferencias        VARCHAR(500),
    alergias                VARCHAR(500),
    precisa_vaga_carro      VARCHAR(3),
    precisa_vaga_moto       VARCHAR(3),
    atualizado_em           TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_perfis_usuario_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_perfis_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_perfis_usuario_fumo CHECK (habito_fumo IS NULL OR habito_fumo IN
        ('NAO_FUMO', 'FUMO_SOCIALMENTE', 'FUMO_QUANDO_BEBO', 'FUMANTE', 'TENTANDO_PARAR')),
    CONSTRAINT ck_perfis_usuario_bebida CHECK (habito_bebida IS NULL OR habito_bebida IN
        ('NAO_CURTO', 'PAREI_DE_BEBER', 'BEBO_COM_MODERACAO', 'OCASIOES_ESPECIAIS', 'SOCIALMENTE_FDS', 'QUASE_TODA_NOITE')),
    CONSTRAINT ck_perfis_usuario_alimentacao CHECK (alimentacao IS NULL OR alimentacao IN
        ('ONIVORO', 'VEGETARIANO', 'VEGANO', 'PESCETARIANO', 'FLEXITARIANO', 'OUTRO')),
    CONSTRAINT ck_perfis_usuario_sexo CHECK (sexo IS NULL OR sexo IN ('MASCULINO', 'FEMININO', 'OUTRO')),
    CONSTRAINT ck_perfis_usuario_precisa_vaga CHECK (
        (precisa_vaga_carro IS NULL OR precisa_vaga_carro IN ('SIM', 'NAO'))
        AND (precisa_vaga_moto IS NULL OR precisa_vaga_moto IN ('SIM', 'NAO')))
);

CREATE TABLE anuncios (
    id                      BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id              BIGINT              NOT NULL,
    tipo                    VARCHAR(20)         NOT NULL,
    titulo                  VARCHAR(160)        NOT NULL,
    descricao               VARCHAR(2000),
    bairro_preferido        VARCHAR(160),
    faculdade_proxima       VARCHAR(160),
    preco                   NUMERIC(10, 2),
    vagas_disponiveis       INTEGER,
    sexo_aceito             VARCHAR(20)         NOT NULL DEFAULT 'QUALQUER',
    endereco                VARCHAR(255),
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    aceita_pets             VARCHAR(3),
    aceita_fumante          VARCHAR(3),
    dormitorios             INTEGER,
    suites                  INTEGER,
    banheiros_sociais       INTEGER,
    vagas_garagem           INTEGER,
    garagem_carro           VARCHAR(3),
    garagem_moto            VARCHAR(3),
    garagem_disposicao      VARCHAR(20),
    garagem_coberta         VARCHAR(3),
    piscina                 VARCHAR(3),
    salao_festas            VARCHAR(3),
    academia                VARCHAR(3),
    playground              VARCHAR(3),
    portaria_24h            VARCHAR(3),
    ativo                   VARCHAR(3)          NOT NULL DEFAULT 'SIM',
    disponivel              VARCHAR(3)          NOT NULL DEFAULT 'SIM',
    fechado_com_usuario_id  BIGINT,
    fechado_em              TIMESTAMP,
    expira_em               TIMESTAMP,
    destaque_ate            TIMESTAMP,
    criado_em               TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_anuncios_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_anuncios_fechado_com FOREIGN KEY (fechado_com_usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_anuncios_tipo CHECK (tipo IN ('TEM_VAGA', 'ESTABELECIMENTO')),
    CONSTRAINT ck_anuncios_sexo_aceito CHECK (sexo_aceito IN ('QUALQUER', 'MASCULINO', 'FEMININO')),
    CONSTRAINT ck_anuncios_ativo CHECK (ativo IN ('SIM', 'NAO')),
    CONSTRAINT ck_anuncios_disponivel CHECK (disponivel IN ('SIM', 'NAO')),
    CONSTRAINT ck_anuncios_aceita CHECK (
        (aceita_pets IS NULL OR aceita_pets IN ('SIM', 'NAO'))
        AND (aceita_fumante IS NULL OR aceita_fumante IN ('SIM', 'NAO'))),
    CONSTRAINT ck_anuncios_detalhes_qtd CHECK (
        (dormitorios IS NULL OR dormitorios >= 0)
        AND (suites IS NULL OR suites >= 0)
        AND (banheiros_sociais IS NULL OR banheiros_sociais >= 0)
        AND (vagas_garagem IS NULL OR vagas_garagem >= 0)),
    CONSTRAINT ck_anuncios_detalhes_simnao CHECK (
        (garagem_carro IS NULL OR garagem_carro IN ('SIM', 'NAO'))
        AND (garagem_moto IS NULL OR garagem_moto IN ('SIM', 'NAO'))
        AND (garagem_coberta IS NULL OR garagem_coberta IN ('SIM', 'NAO'))
        AND (piscina IS NULL OR piscina IN ('SIM', 'NAO'))
        AND (salao_festas IS NULL OR salao_festas IN ('SIM', 'NAO'))
        AND (academia IS NULL OR academia IN ('SIM', 'NAO'))
        AND (playground IS NULL OR playground IN ('SIM', 'NAO'))
        AND (portaria_24h IS NULL OR portaria_24h IN ('SIM', 'NAO'))),
    CONSTRAINT ck_anuncios_garagem_disposicao CHECK (garagem_disposicao IS NULL OR garagem_disposicao IN ('GAVETA', 'LATERAL'))
);

CREATE INDEX idx_anuncios_usuario ON anuncios (usuario_id);
CREATE INDEX idx_anuncios_tipo_ativo ON anuncios (tipo, ativo);

-- conversas, mensagens, pagamentos, notificacoes, bloqueios e denuncias usam sequência (não
-- IDENTITY): são as tabelas com RLS (V2), e o "INSERT ... RETURNING id" que o Hibernate faz para
-- IDENTITY também checa a política de SELECT da linha retornada — quebra sempre que a linha é
-- inserida para outra pessoa (ex.: notificação para o dono do anúncio). SEQUENCE não usa RETURNING.
CREATE SEQUENCE seq_conversas INCREMENT BY 1;
CREATE SEQUENCE seq_mensagens INCREMENT BY 1;
CREATE SEQUENCE seq_pagamentos INCREMENT BY 1;
CREATE SEQUENCE seq_notificacoes INCREMENT BY 1;
CREATE SEQUENCE seq_bloqueios INCREMENT BY 1;
CREATE SEQUENCE seq_denuncias INCREMENT BY 1;

CREATE TABLE conversas (
    id              BIGINT      PRIMARY KEY DEFAULT nextval('seq_conversas'),
    anuncio_id      BIGINT      NOT NULL,
    inquilino_id    BIGINT      NOT NULL,
    usuario2_id     BIGINT,
    criado_em       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_conversas_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversas_inquilino FOREIGN KEY (inquilino_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversas_usuario2 FOREIGN KEY (usuario2_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE INDEX idx_conversas_inquilino ON conversas (inquilino_id);

-- No máximo uma conversa por (anúncio, inquilino) com o dono.
CREATE UNIQUE INDEX uq_conversas_com_dono ON conversas (
    (CASE WHEN usuario2_id IS NULL THEN anuncio_id END),
    (CASE WHEN usuario2_id IS NULL THEN inquilino_id END)
);

-- No máximo uma conversa por (anúncio, par de interessados), independente de quem iniciou:
-- usa o menor/maior id do par para o índice enxergar os dois sentidos como a mesma combinação.
CREATE UNIQUE INDEX uq_conversas_entre_interessados ON conversas (
    (CASE WHEN usuario2_id IS NOT NULL THEN anuncio_id END),
    (CASE WHEN usuario2_id IS NOT NULL THEN LEAST(inquilino_id, usuario2_id) END),
    (CASE WHEN usuario2_id IS NOT NULL THEN GREATEST(inquilino_id, usuario2_id) END)
);

CREATE TABLE mensagens (
    id                  BIGINT              PRIMARY KEY DEFAULT nextval('seq_mensagens'),
    conversa_id         BIGINT              NOT NULL,
    remetente_id        BIGINT              NOT NULL,
    conteudo            VARCHAR(2000)       NOT NULL,
    enviado_em          TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mensagens_conversa FOREIGN KEY (conversa_id) REFERENCES conversas (id) ON DELETE CASCADE,
    CONSTRAINT fk_mensagens_remetente FOREIGN KEY (remetente_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE INDEX idx_mensagens_conversa ON mensagens (conversa_id, enviado_em);

CREATE TABLE interesses (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anuncio_id  BIGINT      NOT NULL,
    usuario_id  BIGINT      NOT NULL,
    criado_em   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interesses_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE CASCADE,
    CONSTRAINT fk_interesses_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT uq_interesses_anuncio_usuario UNIQUE (anuncio_id, usuario_id)
);

CREATE INDEX idx_interesses_usuario ON interesses (usuario_id);

CREATE TABLE pagamentos (
    id                      BIGINT              PRIMARY KEY DEFAULT nextval('seq_pagamentos'),
    usuario_id              BIGINT              NOT NULL,
    anuncio_id              BIGINT,
    tipo                    VARCHAR(20)         NOT NULL,
    valor                   NUMERIC(10, 2)      NOT NULL,
    status                  VARCHAR(20)         NOT NULL,
    referencia_externa      VARCHAR(100),
    criado_em               TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pago_em                 TIMESTAMP,
    versao                  BIGINT              NOT NULL DEFAULT 0,
    gateway                 VARCHAR(20),
    link_pagamento          VARCHAR(500),
    gateway_pagamento_id    VARCHAR(40),
    metodo                  VARCHAR(30),
    status_gateway          VARCHAR(30),
    reembolsado_em          TIMESTAMP,
    reembolsado_por_id      BIGINT,
    motivo_reembolso        VARCHAR(500),
    CONSTRAINT fk_pagamentos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_pagamentos_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE SET NULL,
    CONSTRAINT fk_pagamentos_reembolsado_por FOREIGN KEY (reembolsado_por_id) REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_pagamentos_tipo CHECK (tipo IN ('ANUNCIO_EXTRA', 'DESTAQUE')),
    CONSTRAINT ck_pagamentos_status CHECK (status IN ('PENDENTE', 'PAGO', 'CANCELADO', 'REEMBOLSADO'))
);

CREATE INDEX idx_pagamentos_usuario ON pagamentos (usuario_id, status);
CREATE INDEX idx_pagamentos_anuncio ON pagamentos (anuncio_id);

CREATE TABLE convivios (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario1_id     BIGINT      NOT NULL,
    usuario2_id     BIGINT      NOT NULL,
    proposto_por_id BIGINT      NOT NULL,
    periodo_inicio  DATE        NOT NULL,
    periodo_fim     DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmado_em   TIMESTAMP,
    CONSTRAINT fk_convivios_usuario1 FOREIGN KEY (usuario1_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_convivios_usuario2 FOREIGN KEY (usuario2_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_convivios_proposto_por FOREIGN KEY (proposto_por_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_convivios_status CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'RECUSADO')),
    CONSTRAINT ck_convivios_par_ordenado CHECK (usuario1_id < usuario2_id),
    CONSTRAINT uq_convivios_par UNIQUE (usuario1_id, usuario2_id)
);

CREATE INDEX idx_convivios_usuario2 ON convivios (usuario2_id);

CREATE TABLE avaliacoes (
    id                  BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    convivio_id         BIGINT              NOT NULL,
    avaliador_id        BIGINT              NOT NULL,
    avaliado_id         BIGINT              NOT NULL,
    nota_pontualidade   INTEGER             NOT NULL,
    nota_convivencia    INTEGER             NOT NULL,
    comentario          VARCHAR(1000),
    criado_em           TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_avaliacoes_convivio  FOREIGN KEY (convivio_id) REFERENCES convivios (id) ON DELETE CASCADE,
    CONSTRAINT fk_avaliacoes_avaliador FOREIGN KEY (avaliador_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_avaliacoes_avaliado  FOREIGN KEY (avaliado_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_avaliacoes_notas CHECK (nota_pontualidade BETWEEN 1 AND 5 AND nota_convivencia BETWEEN 1 AND 5),
    CONSTRAINT ck_avaliacoes_pessoas_diferentes CHECK (avaliador_id <> avaliado_id),
    CONSTRAINT uq_avaliacoes_convivio_avaliador UNIQUE (convivio_id, avaliador_id)
);

CREATE INDEX idx_avaliacoes_avaliado ON avaliacoes (avaliado_id);

CREATE TABLE notificacoes (
    id          BIGINT              PRIMARY KEY DEFAULT nextval('seq_notificacoes'),
    usuario_id  BIGINT              NOT NULL,
    tipo        VARCHAR(30)         NOT NULL,
    titulo      VARCHAR(160)        NOT NULL,
    mensagem    VARCHAR(500),
    link        VARCHAR(200),
    lida        VARCHAR(3)          NOT NULL DEFAULT 'NAO',
    criado_em   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notificacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_notificacoes_tipo CHECK (tipo IN (
        'NOVA_MENSAGEM', 'NOVA_CONVERSA', 'CONVIVIO_PROPOSTO', 'CONVIVIO_CONFIRMADO',
        'CONVIVIO_RECUSADO', 'AVALIACAO_RECEBIDA', 'NOVO_INTERESSE', 'INTERESSE_EM_COMUM'
    )),
    CONSTRAINT ck_notificacoes_lida CHECK (lida IN ('SIM', 'NAO'))
);

CREATE INDEX idx_notificacoes_usuario ON notificacoes (usuario_id, criado_em);

CREATE TABLE bloqueios (
    id              BIGINT              PRIMARY KEY DEFAULT nextval('seq_bloqueios'),
    usuario_id      BIGINT              NOT NULL,
    bloqueado_id    BIGINT              NOT NULL,
    criado_em       TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bloqueios_usuario   FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_bloqueios_bloqueado FOREIGN KEY (bloqueado_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_bloqueios_diferentes CHECK (usuario_id <> bloqueado_id),
    CONSTRAINT uq_bloqueios_par UNIQUE (usuario_id, bloqueado_id)
);

CREATE INDEX idx_bloqueios_bloqueado ON bloqueios (bloqueado_id);

CREATE TABLE denuncias (
    id                  BIGINT              PRIMARY KEY DEFAULT nextval('seq_denuncias'),
    denunciante_id      BIGINT              NOT NULL,
    denunciado_id       BIGINT              NOT NULL,
    conversa_id         BIGINT,
    motivo              VARCHAR(30)         NOT NULL,
    descricao           VARCHAR(1000),
    criado_em           TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status              VARCHAR(20)         NOT NULL DEFAULT 'ABERTA',
    resolvida_em        TIMESTAMP,
    resolvida_por_id    BIGINT,
    nota_admin          VARCHAR(1000),
    CONSTRAINT fk_denuncias_denunciante FOREIGN KEY (denunciante_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_denuncias_denunciado  FOREIGN KEY (denunciado_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_denuncias_conversa    FOREIGN KEY (conversa_id) REFERENCES conversas (id) ON DELETE SET NULL,
    CONSTRAINT fk_denuncias_resolvida_por FOREIGN KEY (resolvida_por_id) REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_denuncias_motivo CHECK (motivo IN (
        'COMPORTAMENTO_SUSPEITO', 'GOLPE_OU_FRAUDE', 'CONTEUDO_IMPROPRIO', 'ASSEDIO', 'OUTRO'
    )),
    CONSTRAINT ck_denuncias_status CHECK (status IN ('ABERTA', 'RESOLVIDA', 'DESCARTADA')),
    CONSTRAINT ck_denuncias_diferentes CHECK (denunciante_id <> denunciado_id)
);

CREATE INDEX idx_denuncias_denunciado ON denuncias (denunciado_id);
CREATE INDEX idx_denuncias_status ON denuncias (status, criado_em);

CREATE TABLE redefinicoes_senha (
    id          BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT              NOT NULL,
    token_hash  VARCHAR(64)         NOT NULL,
    usado       VARCHAR(3)          NOT NULL DEFAULT 'NAO',
    criado_em   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em   TIMESTAMP           NOT NULL,
    CONSTRAINT fk_redefinicoes_senha_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_redefinicoes_senha_usado CHECK (usado IN ('SIM', 'NAO'))
);

CREATE UNIQUE INDEX uq_redefinicoes_senha_token ON redefinicoes_senha (token_hash);
CREATE INDEX idx_redefinicoes_senha_usuario ON redefinicoes_senha (usuario_id);

CREATE TABLE confirmacoes_email (
    id          BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT              NOT NULL,
    token_hash  VARCHAR(64)         NOT NULL,
    usado       VARCHAR(3)          NOT NULL DEFAULT 'NAO',
    criado_em   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expira_em   TIMESTAMP           NOT NULL,
    CONSTRAINT fk_confirmacoes_email_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_confirmacoes_email_usado CHECK (usado IN ('SIM', 'NAO'))
);

CREATE UNIQUE INDEX uq_confirmacoes_email_token ON confirmacoes_email (token_hash);
CREATE INDEX idx_confirmacoes_email_usuario ON confirmacoes_email (usuario_id);

CREATE TABLE fotos_usuario (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT              NOT NULL,
    conteudo        BYTEA               NOT NULL,
    tipo_conteudo   VARCHAR(50)         NOT NULL,
    atualizado_em   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fotos_usuario_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_fotos_usuario_usuario ON fotos_usuario (usuario_id);

CREATE TABLE fotos_anuncio (
    id              BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anuncio_id      BIGINT              NOT NULL,
    conteudo        BYTEA               NOT NULL,
    tipo_conteudo   VARCHAR(50)         NOT NULL,
    ordem           INTEGER             NOT NULL DEFAULT 0,
    criado_em       TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fotos_anuncio_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE CASCADE
);

CREATE INDEX idx_fotos_anuncio_anuncio ON fotos_anuncio (anuncio_id);

-- Registros de acesso (Marco Civil da Internet, Lei 12.965/2014, art. 15). Gravados via JDBC puro
-- (AccessLogService), não pelo Hibernate; RLS (V2) impede qualquer usuário comum de ler ou apagar.
CREATE TABLE registros_acesso (
    id          BIGINT              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT,
    ip          VARCHAR(45)         NOT NULL,
    porta       INTEGER,
    evento      VARCHAR(20)         NOT NULL,
    metodo      VARCHAR(10),
    rota        VARCHAR(200),
    status      INTEGER,
    criado_em   TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_registros_acesso_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_registros_acesso_evento CHECK (evento IN (
        'LOGIN', 'LOGIN_FALHOU', 'CADASTRO', 'LOGOUT', 'SENHA_REDEFINIDA', 'CONTA_EXCLUIDA', 'ACESSO'
    ))
);

CREATE INDEX idx_registros_acesso_data ON registros_acesso (criado_em);
CREATE INDEX idx_registros_acesso_usuario ON registros_acesso (usuario_id, criado_em);
CREATE INDEX idx_registros_acesso_ip ON registros_acesso (ip, criado_em);
