-- Registros de acesso à aplicação (Marco Civil da Internet, Lei 12.965/2014, art. 15): data e hora
-- de uso a partir de um IP, guardados por 6 meses e entregues só com ordem judicial.
-- Gravados pelo backend (AccessLogFilter/AccessLogService); apagados sozinhos depois do prazo.
--   evento: LOGIN, LOGIN_FALHOU, CADASTRO, LOGOUT, SENHA_REDEFINIDA, CONTA_EXCLUIDA ou ACESSO
--           (ACESSO = uso comum, agrupado em no máximo 1 linha a cada 5 min por conta + IP)
--   porta : porta de origem do cliente; com IP compartilhado pela operadora (CGNAT), só o IP não
--           identifica ninguém.
CREATE TABLE registros_acesso (
    id          NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER,
    ip          VARCHAR2(45 CHAR)   NOT NULL,
    porta       NUMBER(5),
    evento      VARCHAR2(20 CHAR)   NOT NULL,
    metodo      VARCHAR2(10 CHAR),
    rota        VARCHAR2(200 CHAR),
    status      NUMBER(3),
    criado_em   TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_registros_acesso_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_registros_acesso_evento CHECK (evento IN (
        'LOGIN', 'LOGIN_FALHOU', 'CADASTRO', 'LOGOUT', 'SENHA_REDEFINIDA', 'CONTA_EXCLUIDA', 'ACESSO'
    ))
);

CREATE INDEX idx_registros_acesso_data ON registros_acesso (criado_em);
CREATE INDEX idx_registros_acesso_usuario ON registros_acesso (usuario_id, criado_em);
CREATE INDEX idx_registros_acesso_ip ON registros_acesso (ip, criado_em);

-- RLS: nenhum usuário do site lê, altera ou apaga os registros (a função rls_predicado da V29
-- devolve "1 = 0" para tabelas que não conhece). Só tarefas internas e admins, pelo banco.
BEGIN
    DBMS_RLS.ADD_POLICY(
        object_schema   => USER,
        object_name     => 'REGISTROS_ACESSO',
        policy_name     => 'RLS_REGISTROS_ACESSO',
        function_schema => USER,
        policy_function => 'RLS_PREDICADO',
        statement_types => 'SELECT, UPDATE, DELETE',
        update_check    => TRUE,
        policy_type     => DBMS_RLS.DYNAMIC
    );
END;
/
