-- Confirmação de e-mail no cadastro: prova que a pessoa é dona do e-mail (evita contas criadas
-- com o e-mail de outra pessoa). Até confirmar, a conta não anuncia, não conversa e não
-- demonstra interesse.
ALTER TABLE usuarios ADD email_confirmado_em TIMESTAMP;

-- Quem já tinha conta antes desta regra fica como confirmado (ninguém é travado de repente).
UPDATE usuarios SET email_confirmado_em = criado_em;

-- Links de confirmação: como em redefinicoes_senha, só o hash SHA-256 do token é guardado.
CREATE TABLE confirmacoes_email (
    id          NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER              NOT NULL,
    token_hash  VARCHAR2(64 CHAR)   NOT NULL,
    usado       VARCHAR2(3 CHAR)    DEFAULT 'NAO' NOT NULL,
    criado_em   TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    expira_em   TIMESTAMP           NOT NULL,
    CONSTRAINT fk_confirmacoes_email_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_confirmacoes_email_usado CHECK (usado IN ('SIM', 'NAO'))
);

CREATE UNIQUE INDEX uq_confirmacoes_email_token ON confirmacoes_email (token_hash);
CREATE INDEX idx_confirmacoes_email_usuario ON confirmacoes_email (usuario_id);
