-- Cobrança: os 3 primeiros anúncios de quem anuncia são grátis; a partir do 4º é
-- preciso comprar um "anúncio extra" (válido por N dias). Qualquer anúncio pode
-- ganhar "destaque" pago (aparece no topo da busca por N dias).

-- expira_em     : só anúncios extras (pagos) têm validade; NULL = anúncio grátis, sem validade.
-- destaque_ate  : enquanto for maior que o momento atual, o anúncio está em destaque.
ALTER TABLE anuncios ADD (expira_em TIMESTAMP, destaque_ate TIMESTAMP);

CREATE TABLE pagamentos (
    id                  NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          NUMBER              NOT NULL,
    -- DESTAQUE: anúncio que recebeu o destaque.
    -- ANUNCIO_EXTRA: NULL enquanto o crédito não foi usado; depois, o anúncio criado com ele.
    anuncio_id          NUMBER,
    tipo                VARCHAR2(20 CHAR)   NOT NULL,
    valor               NUMBER(10, 2)       NOT NULL,
    status              VARCHAR2(20 CHAR)   NOT NULL,
    referencia_externa  VARCHAR2(100 CHAR),
    criado_em           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    pago_em             TIMESTAMP,
    versao              NUMBER              DEFAULT 0 NOT NULL,
    CONSTRAINT fk_pagamentos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_pagamentos_anuncio FOREIGN KEY (anuncio_id) REFERENCES anuncios (id) ON DELETE SET NULL,
    CONSTRAINT ck_pagamentos_tipo CHECK (tipo IN ('ANUNCIO_EXTRA', 'DESTAQUE')),
    CONSTRAINT ck_pagamentos_status CHECK (status IN ('PENDENTE', 'PAGO', 'CANCELADO'))
);

CREATE INDEX idx_pagamentos_usuario ON pagamentos (usuario_id, status);
CREATE INDEX idx_pagamentos_anuncio ON pagamentos (anuncio_id);
