-- Avaliação entre usuários: só quem realmente morou junto pode avaliar o outro.
-- "Morou junto" vira registro só depois que os dois confirmam um convívio (proposto por
-- um deles, com o período em que ficaram na mesma moradia); a partir daí, cada lado pode
-- registrar uma avaliação sobre o outro para aquele convívio.

CREATE TABLE convivios (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario1_id     NUMBER              NOT NULL,
    usuario2_id     NUMBER              NOT NULL,
    proposto_por_id NUMBER              NOT NULL,
    periodo_inicio  DATE                NOT NULL,
    periodo_fim     DATE,
    status          VARCHAR2(20 CHAR)   DEFAULT 'PENDENTE' NOT NULL,
    criado_em       TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    confirmado_em   TIMESTAMP,
    CONSTRAINT fk_convivios_usuario1 FOREIGN KEY (usuario1_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_convivios_usuario2 FOREIGN KEY (usuario2_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_convivios_proposto_por FOREIGN KEY (proposto_por_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_convivios_status CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'RECUSADO')),
    -- usuario1_id < usuario2_id dá um par canônico, então o índice único abaixo vale
    -- independente de quem propôs o convívio.
    CONSTRAINT ck_convivios_par_ordenado CHECK (usuario1_id < usuario2_id),
    CONSTRAINT uq_convivios_par UNIQUE (usuario1_id, usuario2_id)
);

CREATE INDEX idx_convivios_usuario2 ON convivios (usuario2_id);

CREATE TABLE avaliacoes (
    id                  NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    convivio_id         NUMBER              NOT NULL,
    avaliador_id        NUMBER              NOT NULL,
    avaliado_id         NUMBER              NOT NULL,
    nota_pontualidade   NUMBER(1)           NOT NULL,
    nota_convivencia    NUMBER(1)           NOT NULL,
    comentario          VARCHAR2(1000 CHAR),
    criado_em           TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_avaliacoes_convivio  FOREIGN KEY (convivio_id) REFERENCES convivios (id) ON DELETE CASCADE,
    CONSTRAINT fk_avaliacoes_avaliador FOREIGN KEY (avaliador_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_avaliacoes_avaliado  FOREIGN KEY (avaliado_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_avaliacoes_notas CHECK (
        nota_pontualidade BETWEEN 1 AND 5 AND nota_convivencia BETWEEN 1 AND 5
    ),
    CONSTRAINT ck_avaliacoes_pessoas_diferentes CHECK (avaliador_id <> avaliado_id),
    -- cada lado do convívio só pode avaliar o outro uma vez
    CONSTRAINT uq_avaliacoes_convivio_avaliador UNIQUE (convivio_id, avaliador_id)
);

CREATE INDEX idx_avaliacoes_avaliado ON avaliacoes (avaliado_id);
