-- Notificações internas: cada evento relevante (mensagem nova, conversa iniciada, convívio,
-- avaliação recebida) vira uma linha aqui. O front consulta periodicamente, no mesmo padrão
-- de polling já usado no chat (não há push/websocket na aplicação).
CREATE TABLE notificacoes (
    id          NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER              NOT NULL,
    tipo        VARCHAR2(30 CHAR)   NOT NULL,
    titulo      VARCHAR2(160 CHAR)  NOT NULL,
    mensagem    VARCHAR2(500 CHAR),
    link        VARCHAR2(200 CHAR),
    lida        VARCHAR2(3 CHAR)    DEFAULT 'NAO' NOT NULL,
    criado_em   TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_notificacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_notificacoes_tipo CHECK (tipo IN (
        'NOVA_MENSAGEM', 'NOVA_CONVERSA', 'CONVIVIO_PROPOSTO', 'CONVIVIO_CONFIRMADO',
        'CONVIVIO_RECUSADO', 'AVALIACAO_RECEBIDA'
    )),
    CONSTRAINT ck_notificacoes_lida CHECK (lida IN ('SIM', 'NAO'))
);

CREATE INDEX idx_notificacoes_usuario ON notificacoes (usuario_id, criado_em);
