-- Bloqueio: ação unilateral, não depende da outra parte concordar. Enquanto existir, os dois
-- usuários somem um para o outro na busca e não conseguem trocar novas mensagens.
CREATE TABLE bloqueios (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER              NOT NULL,
    bloqueado_id    NUMBER              NOT NULL,
    criado_em       TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bloqueios_usuario   FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_bloqueios_bloqueado FOREIGN KEY (bloqueado_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT ck_bloqueios_diferentes CHECK (usuario_id <> bloqueado_id),
    CONSTRAINT uq_bloqueios_par UNIQUE (usuario_id, bloqueado_id)
);

CREATE INDEX idx_bloqueios_bloqueado ON bloqueios (bloqueado_id);

-- Denúncia: fica registrada para consulta futura de moderação. A pessoa denunciada não é
-- avisada (evita retaliação); só quem denunciou recebe a confirmação de que foi registrada.
CREATE TABLE denuncias (
    id              NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denunciante_id  NUMBER              NOT NULL,
    denunciado_id   NUMBER              NOT NULL,
    conversa_id     NUMBER,
    motivo          VARCHAR2(30 CHAR)   NOT NULL,
    descricao       VARCHAR2(1000 CHAR),
    criado_em       TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_denuncias_denunciante FOREIGN KEY (denunciante_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_denuncias_denunciado  FOREIGN KEY (denunciado_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_denuncias_conversa    FOREIGN KEY (conversa_id) REFERENCES conversas (id) ON DELETE SET NULL,
    CONSTRAINT ck_denuncias_motivo CHECK (motivo IN (
        'COMPORTAMENTO_SUSPEITO', 'GOLPE_OU_FRAUDE', 'CONTEUDO_IMPROPRIO', 'ASSEDIO', 'OUTRO'
    )),
    CONSTRAINT ck_denuncias_diferentes CHECK (denunciante_id <> denunciado_id)
);

CREATE INDEX idx_denuncias_denunciado ON denuncias (denunciado_id);
